# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hollow Moon
email: hollowmoontl@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Translation of TYPE-MOON works into English.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hollow-moon.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: HollowMoonTL
github_username: Hollow-Moon

paginate: 5

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    sourcemap: development

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - .devcontainer
